// <auto-generated />
using System;
using System.Collections.Generic;
using Delegation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Delegation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DelegationDbContext))]
    [Migration("20260327113504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delegation")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Delegation.Domain.Entities.DelegationGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChainDepth")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DelegateeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DelegatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("_permissionCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permission_codes");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExpiresAt")
                        .HasDatabaseName("IX_Delegations_TenantId_ExpiresAt");

                    b.HasIndex("TenantId", "DelegateeId", "IsRevoked")
                        .HasDatabaseName("IX_Delegations_TenantId_DelegateeId_IsRevoked");

                    b.HasIndex("TenantId", "DelegatorId", "IsRevoked")
                        .HasDatabaseName("IX_Delegations_TenantId_DelegatorId_IsRevoked");

                    b.ToTable("Delegations", "delegation");
                });
#pragma warning restore 612, 618
        }
    }
}
